services:
  petshopfrontend:
    build: ./petshop-front/
    container_name: "petshopfrontend"
    ports:
      - 80:80
  productscatalogapi:
    build: ./productscatalogapi/
    container_name: "productscatalogapi"
    ports:
      - 8080:8080
    depends_on:
      - productscatalog-mysql
    networks:
      - petshop_network
  usersapi:
    build: ./usersapi/
    container_name: "usersapi"
    ports:
      - 8081:8081
    depends_on:
      - users-mysql
    networks:
      - petshop_network
  ordersapi:
    build: ./ordersapi/
    container_name: "ordersapi"
    ports:
      - 8082:8082
    depends_on:
      - orders-mysql
    networks:
      - petshop_network
  paymentsapi:
    build: ./paymentsapi/
    container_name: "paymentsapi"
    ports:
      - 8083:8083
    depends_on:
      - payments-mysql
    networks:
      - petshop_network
  productscatalog-mysql:
    image: mysql:8.0.30
    container_name: "productscatalog-mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_products
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - petshop_network
  users-mysql:
    image: mysql:8.0.30
    container_name: "users-mysql"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_users
    networks:
      - petshop_network
  orders-mysql:
    image: mysql:8.0.30
    container_name: "orders-mysql"
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_orders
    networks:
      - petshop_network
  payments-mysql:
    image: mysql:8.0.30
    container_name: "payments-mysql"
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_payments
    networks:
      - petshop_network

networks:
  petshop_network:
    driver: bridge